#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSP.DataManager.DataClasses
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NezamFars")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClassesDataContext() : 
                //base(global::TSP.DataManager.Properties.Settings.Default.NezamFarsConnectionString2, mappingSource)
        base(DBManager.CnnStr, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ReportMemberWithoutDocByMajor")]
		public ISingleResult<ReportMemberWithoutDocByMajorResult> ReportMemberWithoutDocByMajor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SexIdFemale", DbType="Int")] System.Nullable<int> sexIdFemale, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SexIdmale", DbType="Int")] System.Nullable<int> sexIdmale, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Memari", DbType="Int")] System.Nullable<int> memari, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> shahrsazi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Omran", DbType="Int")] System.Nullable<int> omran, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mechanic", DbType="Int")] System.Nullable<int> mechanic, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Bargh", DbType="Int")] System.Nullable<int> bargh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Naghshebardari", DbType="Int")] System.Nullable<int> naghshebardari, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> traffic)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sexIdFemale, sexIdmale, memari, shahrsazi, omran, mechanic, bargh, naghshebardari, traffic);
			return ((ISingleResult<ReportMemberWithoutDocByMajorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ReportMemberWithDocByMajor")]
		public ISingleResult<ReportMemberWithDocByMajorResult> ReportMemberWithDocByMajor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TableTypeMajor", DbType="Int")] System.Nullable<int> tableTypeMajor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TableType", DbType="Int")] System.Nullable<int> tableType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SexId", DbType="Int")] System.Nullable<int> sexId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GrdId3", DbType="Int")] System.Nullable<int> grdId3, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GrdId2", DbType="Int")] System.Nullable<int> grdId2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GrdId1", DbType="Int")] System.Nullable<int> grdId1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GrdIdArshad", DbType="Int")] System.Nullable<int> grdIdArshad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MjParentId", DbType="Int")] System.Nullable<int> mjParentId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tableTypeMajor, tableType, sexId, grdId3, grdId2, grdId1, grdIdArshad, mjParentId);
			return ((ISingleResult<ReportMemberWithDocByMajorResult>)(result.ReturnValue));
		}
	}
	
	public partial class ReportMemberWithoutDocByMajorResult
	{
		
		private System.Nullable<int> _MemariFemale;
		
		private System.Nullable<int> _MemariMale;
		
		private System.Nullable<int> _ShahrsaziFemale;
		
		private System.Nullable<int> _ShahrsaziMale;
		
		private System.Nullable<int> _OmranFemal;
		
		private System.Nullable<int> _OmranMale;
		
		private System.Nullable<int> _MechanicFemale;
		
		private System.Nullable<int> _MechanicMale;
		
		private System.Nullable<int> _BarchFemale;
		
		private System.Nullable<int> _BarghMale;
		
		private System.Nullable<int> _NaghshebardariFemale;
		
		private System.Nullable<int> _NaghshebardariMale;
		
		private System.Nullable<int> _TerafficeFemale;
		
		private System.Nullable<int> _TerafficMale;
		
		public ReportMemberWithoutDocByMajorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemariFemale", DbType="Int")]
		public System.Nullable<int> MemariFemale
		{
			get
			{
				return this._MemariFemale;
			}
			set
			{
				if ((this._MemariFemale != value))
				{
					this._MemariFemale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemariMale", DbType="Int")]
		public System.Nullable<int> MemariMale
		{
			get
			{
				return this._MemariMale;
			}
			set
			{
				if ((this._MemariMale != value))
				{
					this._MemariMale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShahrsaziFemale", DbType="Int")]
		public System.Nullable<int> ShahrsaziFemale
		{
			get
			{
				return this._ShahrsaziFemale;
			}
			set
			{
				if ((this._ShahrsaziFemale != value))
				{
					this._ShahrsaziFemale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShahrsaziMale", DbType="Int")]
		public System.Nullable<int> ShahrsaziMale
		{
			get
			{
				return this._ShahrsaziMale;
			}
			set
			{
				if ((this._ShahrsaziMale != value))
				{
					this._ShahrsaziMale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OmranFemal", DbType="Int")]
		public System.Nullable<int> OmranFemal
		{
			get
			{
				return this._OmranFemal;
			}
			set
			{
				if ((this._OmranFemal != value))
				{
					this._OmranFemal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OmranMale", DbType="Int")]
		public System.Nullable<int> OmranMale
		{
			get
			{
				return this._OmranMale;
			}
			set
			{
				if ((this._OmranMale != value))
				{
					this._OmranMale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MechanicFemale", DbType="Int")]
		public System.Nullable<int> MechanicFemale
		{
			get
			{
				return this._MechanicFemale;
			}
			set
			{
				if ((this._MechanicFemale != value))
				{
					this._MechanicFemale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MechanicMale", DbType="Int")]
		public System.Nullable<int> MechanicMale
		{
			get
			{
				return this._MechanicMale;
			}
			set
			{
				if ((this._MechanicMale != value))
				{
					this._MechanicMale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarchFemale", DbType="Int")]
		public System.Nullable<int> BarchFemale
		{
			get
			{
				return this._BarchFemale;
			}
			set
			{
				if ((this._BarchFemale != value))
				{
					this._BarchFemale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarghMale", DbType="Int")]
		public System.Nullable<int> BarghMale
		{
			get
			{
				return this._BarghMale;
			}
			set
			{
				if ((this._BarghMale != value))
				{
					this._BarghMale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NaghshebardariFemale", DbType="Int")]
		public System.Nullable<int> NaghshebardariFemale
		{
			get
			{
				return this._NaghshebardariFemale;
			}
			set
			{
				if ((this._NaghshebardariFemale != value))
				{
					this._NaghshebardariFemale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NaghshebardariMale", DbType="Int")]
		public System.Nullable<int> NaghshebardariMale
		{
			get
			{
				return this._NaghshebardariMale;
			}
			set
			{
				if ((this._NaghshebardariMale != value))
				{
					this._NaghshebardariMale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TerafficeFemale", DbType="Int")]
		public System.Nullable<int> TerafficeFemale
		{
			get
			{
				return this._TerafficeFemale;
			}
			set
			{
				if ((this._TerafficeFemale != value))
				{
					this._TerafficeFemale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TerafficMale", DbType="Int")]
		public System.Nullable<int> TerafficMale
		{
			get
			{
				return this._TerafficMale;
			}
			set
			{
				if ((this._TerafficMale != value))
				{
					this._TerafficMale = value;
				}
			}
		}
	}
	
	public partial class ReportMemberWithDocByMajorResult
	{
		
		private System.Nullable<int> _LinkedMajor3;
		
		private System.Nullable<int> _MaindMajor3;
		
		private System.Nullable<int> _LinkedMajor2;
		
		private System.Nullable<int> _MaindMajor2;
		
		private System.Nullable<int> _LinkedMajor1;
		
		private System.Nullable<int> _MaindMajor1;
		
		public ReportMemberWithDocByMajorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkedMajor3", DbType="Int")]
		public System.Nullable<int> LinkedMajor3
		{
			get
			{
				return this._LinkedMajor3;
			}
			set
			{
				if ((this._LinkedMajor3 != value))
				{
					this._LinkedMajor3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaindMajor3", DbType="Int")]
		public System.Nullable<int> MaindMajor3
		{
			get
			{
				return this._MaindMajor3;
			}
			set
			{
				if ((this._MaindMajor3 != value))
				{
					this._MaindMajor3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkedMajor2", DbType="Int")]
		public System.Nullable<int> LinkedMajor2
		{
			get
			{
				return this._LinkedMajor2;
			}
			set
			{
				if ((this._LinkedMajor2 != value))
				{
					this._LinkedMajor2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaindMajor2", DbType="Int")]
		public System.Nullable<int> MaindMajor2
		{
			get
			{
				return this._MaindMajor2;
			}
			set
			{
				if ((this._MaindMajor2 != value))
				{
					this._MaindMajor2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkedMajor1", DbType="Int")]
		public System.Nullable<int> LinkedMajor1
		{
			get
			{
				return this._LinkedMajor1;
			}
			set
			{
				if ((this._LinkedMajor1 != value))
				{
					this._LinkedMajor1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaindMajor1", DbType="Int")]
		public System.Nullable<int> MaindMajor1
		{
			get
			{
				return this._MaindMajor1;
			}
			set
			{
				if ((this._MaindMajor1 != value))
				{
					this._MaindMajor1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
