//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSP.DataManager.LoanWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoanWebService.LoanWebServiceSoap")]
    public interface LoanWebServiceSoap {
        
        // CODEGEN: Generating message contract since message GetSumLoanDebtRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSumLoanDebt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TSP.DataManager.LoanWebService.GetSumLoanDebtResponse GetSumLoanDebt(TSP.DataManager.LoanWebService.GetSumLoanDebtRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthSoapHd : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string strUserNameField;
        
        private string strPasswordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string strUserName {
            get {
                return this.strUserNameField;
            }
            set {
                this.strUserNameField = value;
                this.RaisePropertyChanged("strUserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string strPassword {
            get {
                return this.strPasswordField;
            }
            set {
                this.strPasswordField = value;
                this.RaisePropertyChanged("strPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSumLoanDebt", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSumLoanDebtRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TSP.DataManager.LoanWebService.AuthSoapHd AuthSoapHd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string memCode;
        
        public GetSumLoanDebtRequest() {
        }
        
        public GetSumLoanDebtRequest(TSP.DataManager.LoanWebService.AuthSoapHd AuthSoapHd, string memCode) {
            this.AuthSoapHd = AuthSoapHd;
            this.memCode = memCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSumLoanDebtResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSumLoanDebtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetSumLoanDebtResult;
        
        public GetSumLoanDebtResponse() {
        }
        
        public GetSumLoanDebtResponse(string GetSumLoanDebtResult) {
            this.GetSumLoanDebtResult = GetSumLoanDebtResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoanWebServiceSoapChannel : TSP.DataManager.LoanWebService.LoanWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoanWebServiceSoapClient : System.ServiceModel.ClientBase<TSP.DataManager.LoanWebService.LoanWebServiceSoap>, TSP.DataManager.LoanWebService.LoanWebServiceSoap {
        
        public LoanWebServiceSoapClient() {
        }
        
        public LoanWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoanWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoanWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoanWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TSP.DataManager.LoanWebService.GetSumLoanDebtResponse TSP.DataManager.LoanWebService.LoanWebServiceSoap.GetSumLoanDebt(TSP.DataManager.LoanWebService.GetSumLoanDebtRequest request) {
            return base.Channel.GetSumLoanDebt(request);
        }
        
        public string GetSumLoanDebt(TSP.DataManager.LoanWebService.AuthSoapHd AuthSoapHd, string memCode) {
            TSP.DataManager.LoanWebService.GetSumLoanDebtRequest inValue = new TSP.DataManager.LoanWebService.GetSumLoanDebtRequest();
            inValue.AuthSoapHd = AuthSoapHd;
            inValue.memCode = memCode;
            TSP.DataManager.LoanWebService.GetSumLoanDebtResponse retVal = ((TSP.DataManager.LoanWebService.LoanWebServiceSoap)(this)).GetSumLoanDebt(inValue);
            return retVal.GetSumLoanDebtResult;
        }
    }
}
